;设置规则标志位
surge_ruleset=回国,https://ghp.ci/https://raw.githubusercontent.com/nameless3721/nash/master/rules/yoyuNeteaseMusic.list
surge_ruleset=回国,rules/ConnersHua/Surge/Ruleset/China.list
surge_ruleset=DIRECT,rules/LocalAreaNetwork.list
surge_ruleset=DIRECT,rules/ConnersHua/Surge/Ruleset/Unbreak.list
surge_ruleset=DIRECT,https://ghp.ci/https://raw.githubusercontent.com/nameless3721/nash/master/rules/DIRECT.list
;surge_ruleset=🛑 全球拦截,rules/ConnersHua/Surge/Ruleset/Hijacking.list
;surge_ruleset=🛑 全球拦截,rules/ConnersHua/Surge/Ruleset/Advertising.list
;surge_ruleset=Ⓜ️ 微软服务,rules/MSServices.list
surge_ruleset=油管,rules/ConnersHua/Surge/Ruleset/Media/YouTube.list
surge_ruleset=奶飞,rules/ConnersHua/Surge/Ruleset/Media/Netflix.list
;surge_ruleset=📺 巴哈姆特,rules/ConnersHua/Surge/Ruleset/Media/Bahamut.list
;surge_ruleset=📺 AbemaTV,rules/ConnersHua/Surge/Ruleset/Media/AbemaTV.list
surge_ruleset=电报,rules/ConnersHua/Surge/Ruleset/Telegram.list
surge_ruleset=国外媒体,rules/ConnersHua/Surge/Ruleset/GlobalMedia.list
surge_ruleset=BiliBili,https://raw.nameless13.com/api/public/dl/23yS1MZb/HKMTMedia.list
;surge_ruleset=🍎 苹果服务,rules/ConnersHua/Surge/Ruleset/Apple.list
surge_ruleset=回国,rules/ConnersHua/Surge/Ruleset/Apple.list
surge_ruleset=代理,rules/ConnersHua/Surge/Ruleset/Global.list
surge_ruleset=DIRECT,rules/NobyDa/Surge/Download.list
surge_ruleset=代理,https://ghp.ci/https://raw.githubusercontent.com/nameless3721/nash/master/rules/PROXY.list
surge_ruleset=回国,[]GEOIP,CN
surge_ruleset=国外地址,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=回国`select`GCX`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇺🇲 美国`[]其他`[]手动切换
custom_proxy_group=代理`select`[]DIRECT`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇺🇲 美国`[]其他`[]手动切换`[]回国
;custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`500
custom_proxy_group=电报`select`[]代理`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇺🇲 美国`[]其他`[]手动切换`[]回国
custom_proxy_group=油管`select`[]代理`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇺🇲 美国`[]其他`[]手动切换`[]回国
custom_proxy_group=奶飞`select`[]代理`(NF*)`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇺🇲 美国`[]其他`[]手动切换`[]回国
;custom_proxy_group=📺 巴哈姆特`select`[]🇨🇳 台湾`[]代理`[]其他`[]手动切换`[]回国
;custom_proxy_group=📺 AbemaTV`select`[]🇯🇵 日本`[]代理`[]其他`[]手动切换`[]回国
;custom_proxy_group=🎥 奈非节点`select`(NF|解锁|Netflix|NETFLIX)`[]手动切换`[]回国
custom_proxy_group=手动切换`select`.*`[]DIRECT
custom_proxy_group=国外媒体`select`[]代理`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇺🇲 美国`[]其他`[]手动切换`[]回国
custom_proxy_group=BiliBili`select`[]回国`[]其他`[]🇭🇰 香港`[]🇨🇳 台湾
;custom_proxy_group=🍎 苹果服务`select`[]代理`[]回国`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇺🇲 美国`[]其他`[]手动切换
;custom_proxy_group=Ⓜ️ 微软服务`select`[]代理`[]回国`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇺🇲 美国`[]其他`[]手动切换
;custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]代理`[]🇸🇬 狮城`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]其他`[]手动切换`[]回国
custom_proxy_group=国外地址`select`[]代理`[]回国`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇺🇲 美国`[]其他`[]手动切换
custom_proxy_group=🇭🇰 香港`select`(港|HK|HONG|Hong|HGC)
custom_proxy_group=🇨🇳 台湾`select`(台|新北|彰化|TW|Tai)
custom_proxy_group=🇸🇬 狮城`select`(新|狮城|SG|Singa)
custom_proxy_group=🇯🇵 日本`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap|[^-]日)
custom_proxy_group=🇺🇲 美国`select`(多伦多|哥伦布|纽约|弗里蒙特|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US)
custom_proxy_group=其他`select`GCX`^((?!新|多伦多|哥伦布|纽约|弗里蒙特|Jap|Tai|Singa|狮城|SG|港|HK|HONG|Hong|HGC|台|新北|彰化|TW|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US).)*$
;设置分组标志位
